# Generated by Django 4.1.7 on 2023-05-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=500)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.user')),
            ],
        ),
    ]
